server:
  port: 8081

spring:
  datasource:
    url: 'jdbc:h2:mem:design'
    driver-class-name: org.h2.Driver
    username: design
    password: design
  h2:
    console:
      enabled: true
      path: '/myH2'
  jpa:
    properties:
      hibernate.hbm2ddl.auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  redis:
    host: localhost
    port: 6379

# gitee 第三方登录相关配置
gitee:
  clientId: fbb9e39e63ba02c5d385ecc6b9f5491eabb42e3971bb2815824cec00cfc7122b
  clientSecret: 226c5e9a5bea4040ded6c6357924fb44511e98480bdfc3308c1c730d1a7e7da6
  callBack: http://localhost:8081/gitee
  # 与前端商定的 state 值
  state: GITEE
  user:
    prefix: ${gitee.state}@
    url: https://gitee.com/api/v5/user?access_token=
  token:
    url: https://gitee.com/oauth/token?grant_type=authorization_code&client_id=${gitee.clientId}&client_secret=${gitee.clientSecret}&redirect_uri=${gitee.callBack}&code=